Problem 1. Array Creation

In [ ]:
import numpy as np

# Initialize an empty array of size 2X2
empty_array = np.empty((2, 2))
print("Empty Array of 2X2:\n", empty_array)

# Initialize an all-ones array of size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array of (4X2):\n", ones_array)

#Initialize a size 2x2 array of fill value
fill_value = 8
filled_array = np.full((2, 2), fill_value)
print("\nArray filled with value 8 (2x2):\n", filled_array)

given_array = np.array([[1, 2,], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array with same shape as given array:\n", zeros_like_array)

ones_like_array = np.ones_like(given_array)
print("\nOnes Array with same shape as given array:\n", ones_like_array)

#Converting list into array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array of 2X2:
 [[ 4.71528387e-310  0.00000000e+000]
 [-1.49139240e+243  6.54633130e-310]]

All Ones Array of (4X2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with value 8 (2x2):
 [[8 8]
 [8 8]]

Zeros Array with same shape as given array:
 [[0 0]
 [0 0]]

Ones Array with same shape as given array:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


Problem 2. Array Manipulation

In [ ]:
import numpy as np

#Initialize an array with value ranging from 10 to 49
array_range= np.arange(10, 50)
print("Array Range from 10 to 40:\n", array_range)

#Initialize a 3x3 matrix value from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

#Initialize a 3x3 identity matrix
identity_matrix=np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of the array:", mean_value)



Array Range from 10 to 40:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.99448493 0.45613484 0.9201318  0.60987194 0.57045719 0.18483835
 0.70765227 0.82290773 0.33644111 0.2080903  0.80964951 0.50865798
 0.89309137 0.5108159  0.50802851 0.01806613 0.79144039 0.3759845
 0.70131642 0.94666354 0.53359246 0.7889544  0.94970185 0.75267789
 0.03199472 0.64629467 0.38334252 0.27392007 0.52317169 0.43379554]
Mean of the array: 0.5730723498261763


Problem 3. Array Operations

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Adding two arrays (x and y)
array_addition = x + y
print("1. Addition of x and y:")
print(array_addition)

# Subtracting two arrays (x and y)
array_subtraction = x - y
print("\n2. Subtraction of x and y:")
print(array_subtraction)

# Multiplying the array v by an integer
array_multiplication = v * 2
print("\n3. Multiplication of v by 3:")
print(array_multiplication)

# Finding the square of each element in the array w
array_square = np.square(w)
print("\n4. Square of each element in array w:")
print(array_square)

# Finding the dot product between:
dot_v_w = np.dot(v, w)
print(f"Dot product of v and w: {dot_v_w}")

dot_x_v = np.dot(x, v)
print(f"Dot product of x and v: {dot_x_v}")

dot_x_y = np.dot(x, y)
print(f"Dot product of x and y:\n{dot_x_y}")



# Concatenate x and y along rows, and concatenate v and w along columns
concat_x_y = np.concatenate((x, y), axis=0)  # Row-wise concatenation
concat_v_w = np.vstack((v, w))  # Column-wise concatenation
print("Concatenate x and y along rows:")
print(concat_x_y)
print("Concatenate v and w along columns:")
print(concat_v_w)

# Concatenate x and v; explain the error if any
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\n7. Concatenate x and v along rows:")
    print(concat_x_v)
except ValueError as e:
    print("\n7. Error when concatenating x and v along rows:")
    print(e)

1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of v by 3:
[18 20]

4. Square of each element in array w:
[121 144]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]
Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
[[ 9 10]
 [11 12]]

7. Error when concatenating x and v along rows:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem 4. Matrix Operation

In [ ]:
import numpy as np

# Define the matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove that A * A^(-1) = I (Identity Matrix)
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
identity_matrix = np.dot(A, A_inv)  # Multiply A with its inverse
print("1. Prove A * A^(-1) = I:")
print(identity_matrix)

# 2. Prove that AB ≠ BA
AB = np.dot(A, B)  # Multiply A and B
BA = np.dot(B, A)  # Multiply B and A
print("\n2. Prove AB ≠ BA:")
print("AB =")
print(AB)
print("BA =")
print(BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)  # Transpose of AB
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)  # B^T * A^T
print("\n3. Prove (AB)^T = B^T * A^T:")
print("(AB)^T =")
print(AB_transpose)
print("B^T * A^T =")
print(BT_AT)
print("Are (AB)^T and B^T * A^T equal? ", np.array_equal(AB_transpose, BT_AT))

1. Prove A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. Prove AB ≠ BA:
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
Are AB and BA equal?  False

3. Prove (AB)^T = B^T * A^T:
(AB)^T =
[[23 51]
 [13 29]]
B^T * A^T =
[[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal?  True


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficients matrix
B = np.array([-1, -3, 9])  # Constants matrix

# Solve for X using the inverse method
A_inv = np.linalg.inv(A)  # Inverse of A
X = np.dot(A_inv, B)
print("\nSolution to the system of equations using the inverse method:")
print("X (values of x, y, z) =")
print(X)



Solution to the system of equations using the inverse method:
X (values of x, y, z) =
[ 2.  1. -2.]


1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Element-wise Addition
def element_wise_addition():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    list_result = [list1[i] + list2[i] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Element-wise Addition with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    array_result = array1 + array2
    numpy_time = time.time() - start_time
    print(f"Element-wise Addition with NumPy Arrays: {numpy_time:.4f} seconds")

# Element-wise Multiplication
def element_wise_multiplication():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    list_result = [list1[i] * list2[i] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Element-wise Multiplication with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    array_result = array1 * array2
    numpy_time = time.time() - start_time
    print(f"Element-wise Multiplication with NumPy Arrays: {numpy_time:.4f} seconds")

# Dot Product
def dot_product():
    size = 1_000_000
    list1 = [i for i in range(size)]
    list2 = [i for i in range(size)]
    array1 = np.arange(size)
    array2 = np.arange(size)

    # Using Python Lists
    start_time = time.time()
    dot_product = sum(list1[i] * list2[i] for i in range(size))
    list_time = time.time() - start_time
    print(f"Dot Product with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    dot_product = np.dot(array1, array2)
    numpy_time = time.time() - start_time
    print(f"Dot Product with NumPy Arrays: {numpy_time:.4f} seconds")

# Matrix Multiplication
def matrix_multiplication():
    size = 1000
    matrix1 = [[i for i in range(size)] for _ in range(size)]
    matrix2 = [[i for i in range(size)] for _ in range(size)]
    np_matrix1 = np.array(matrix1)
    np_matrix2 = np.array(matrix2)

    # Using Python Lists
    start_time = time.time()
    result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
    list_time = time.time() - start_time
    print(f"Matrix Multiplication with Python Lists: {list_time:.4f} seconds")

    # Using NumPy Arrays
    start_time = time.time()
    result = np.dot(np_matrix1, np_matrix2)
    numpy_time = time.time() - start_time
    print(f"Matrix Multiplication with NumPy Arrays: {numpy_time:.4f} seconds")

# Run the experiments
element_wise_addition()
element_wise_multiplication()
dot_product()
matrix_multiplication()

Element-wise Addition with Python Lists: 0.1401 seconds
Element-wise Addition with NumPy Arrays: 0.0050 seconds
Element-wise Multiplication with Python Lists: 0.2180 seconds
Element-wise Multiplication with NumPy Arrays: 0.0065 seconds
Dot Product with Python Lists: 0.2742 seconds
Dot Product with NumPy Arrays: 0.0019 seconds
Matrix Multiplication with Python Lists: 243.0573 seconds
Matrix Multiplication with NumPy Arrays: 1.5621 seconds
